# Generated by Django 5.1.6 on 2025-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackfy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetrack',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
