# Generated by Django 5.1.6 on 2025-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackfy', '0002_favoritetrack_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetrack',
            name='album',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
