# Generated by Django 5.1.6 on 2025-03-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackfy', '0003_favoritetrack_album_favoritetrack_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritetrack',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
